language: python
python:
  - "2.7"
install: "pip install -e ."
script:
    - py.test test/unit/ -s -v
    - py.test test/integration/test_logcontains.py -v --rule=test/integration/LOGCONTAINSFIXTURE.yaml
    - py.test test/integration/test_nologcontains.py -v --rule=test/integration/NOLOGCONTAINSFIXTURE.yaml
    - py.test test/integration/test_htmlcontains.py -v --rule=test/integration/HTMLCONTAINSFIXTURE.yaml
    - py.test test/integration/test_http.py -v
    - py.test test/integration/test_cookie.py -v --rule=test/integration/COOKIEFIXTURE.yaml
    - py.test test/integration/test_multipart.py -v --rule=test/integration/MULTIPART.yaml
    - py.test test/integration/test_expecterror.py -s -v --rule=test/integration/EXPECTERRORFIXTURE.yaml
